config/routes.rb
Rails.application.routes.draw do
  get "auth/:provider/callback", to: "connections#create"
  resources :connections, only: [:destroy]
  devise_for :users, controllers: { registrations: "registrations" }
  root 'pages#home'

  get 'dashboard', to: "pages#dashboard"

end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :user

  def self.create_from_omniauth(auth_hash)
    create(
    provider: auth_hash.provider,
    oauth_token: auth_hash.credentials.token,
    secret: auth_hash.credentials.secret
    )
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :time_zone
  has_many :connections, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  around_filter :user_time_zone, if: :current_user

  private

    def user_time_zone(&block)
      Time.use_zone(current_user.time_zone, &block)
    end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  before_action :set_connection, only: [:destroy]
  def create
    connection = current_user.connections.create_from_omniauth(auth_hash)
    if connection.save
      redirect_to dashboard_path, notice: "Connection created!"
    else
      redirect_to dashboard_path, notice: "Something went wrong"
    end
  end

  def destroy
    @connection.destroy
    redirect_to dashboard_path, notice: "Connection deleted"
  end

  private

    def set_connection
      @connection = Connection.find(params[:id])
    end

    def auth_hash
      request.env["omniauth.auth"]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]

  def home
    if current_user
      redirect_to dashboard_path
    end
  end

  def dashboard
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :time_zone)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :time_zone, :current_password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pseudo-Social", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Settings", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PseudoSocial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/header" %>

  <% flash.each do |type, message| %>
  <div class="alert alert-info fade-in">
    <button class="close" data-dismiss="alert" >x</button>
    <%= message %>
  </div>
  
  <div class="container">

    <% end %>

    <%= yield %>

  </div>

</body>
</html>

app/views/pages/dashboard.html.erb
<div class="row">
  <!-- Profile and Connections -->
  <div class="col-md-2 text-center">
    <%= image_tag "images.jpg", class: "logo" %>
    <hr>
    <div class="timezone" >
      <p class="text-center"><b><%= Time.zone.name %> Timezone</b></p>
      <%= link_to "change", edit_user_registration_path %>
    </div>
    <hr>
    <div class="social">
      <% unless current_user.connections.where(provider: "twitter").any? %>
        <%= link_to "Connect with Twitter", 'auth/twitter', class: "btn btn-info btn-block btn-sm" %>
      <% else %>
        <%= link_to "Connect with Twitter", 'auth/twitter', class: "btn btn-info btn-block btn-sm", disabled: true %>
        <%= link_to "Delete Connection", connection_path(current_user.connections.where(provider: "twitter").first), method: :delete %>
      <% end %>
    </div>
  </div>

  <!-- New Post Scheduled -->
  <div class="col-md-5">
    <h3 class="text-center">Scheduled Posts</h3>
    <hr>
  </div>
  <!-- History -->

  <div class="col-md-5">
    <h3 class="text-center">Post History</h3>
    <hr>
  </div>

</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>